language: java
sudo: required
install: true

services:
  - docker
  - mongodb

addons:
  sonarcloud:
    organization: "ljd1987-github"
    token:
      secure: "dmSHV8SFcJc5RHyKQanIxtFhEQs05m97JEsXXBExWq1vLBrv6WUFCvL4mqbO50Nw0wZkOrK0LcZaCJWiNrTbOV3k6YcS81soLPjILpYkRwxIkW8OQL6A9dsr57ATkoXTZIEgUiYOopzHyOLugTbai9EMqq6f2iqUv31pOuU723TZd05O6qWZ74+1krKyk38h/ofiAkYwAPtDic8ZO0rAqXNuq7HN6jKuhfY7VF9vhZAiivKUCbhQD9meF63i01Ce6gN8XALUJ+cubZ5bdRbPQ/CcUykQU6QE8Y1JGap29g5Rxv7smv0MfbpcwAgEwAGlThhKaABIBcqC9oqvUn8b9woFMEWooBO9gIXItBsbcdsn7Gp2ejnSeyD1chSag0T238K4D70B4dd2eMRJ9yWxaVtXP4LXKLcQOF48Za5tyai/HEZLYfy80jp3L3R/7q7/Iziusee+4uBRsmmCXpO4B4Iwy20jskt5SGnKa6JDaKwEpbJLPTs+RZr4gFiT19F56LLvREkGtYgOzyWK54gzehv2zoCeUgby/BRWnR0GFZ8fF0gMtiMPTQJUvvXY8nPZFf+lkvl5SFmxTYfP0FWHIWKuCtsrAkdcWH+rdjbZsBjlfE3EtFypCLsC2A+0UtyUn/T8nhQSvv9m9yImAYF8+b6EqdaTmtntOp+mxB0j9Is="

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar  
  - set -e
  - mvn clean install sonar:sonar
  - cp target/phonebook.war image/
  - docker build -t ljd1987/phonebook image/
  - docker push ljd1987/phonebook