language: java
sudo: required

services:
  - docker
  - mongodb

addons:
  sonarcloud:
    organization: "sonarcloud"
    token:
      secure: "${SONAR_TOKEN}"

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - cp target/phonebook.war image/
  - docker build -t phonebook image/