language: java
sudo: required

services:
  - docker
  - mongodb

addons:
  sonarcloud:
    organization: "ljd1987-github"
    token:
      secure: "${SONAR_TOKEN}"

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar  
  - mvn clean install sonar:sonar
  - cp target/phonebook.war image/
  - docker build -t ljd1987/phonebook image/
  - docker push