version: '2'

services: 

  mongo:
    image: mongo:3.4-jessie

  phonebook:
    image: ljd1987/phonebook
    #image: phonebook # for running against locall built image
    ports:
      - 80:9080
      - 443:9443
    depends_on: 
      - mongo
