swagger: '2.0'

info:
  version: "1.0"
  title: Phonebook API
  description: A simple phonebook api
  
basePath: /api/v1

securityDefinitions:
  basicAuth:
    type: basic

security: 
 - basicAuth: []

paths:
  /contacts:
    post:
      tags:
          - Contacts
      summary: Create a new contact
      description: Creates a new contact resource
      parameters: 
        - name: Contact
          in: body
          description: the JSON representation of the new contact.
          required: true
          schema:
            $ref: '#/definitions/ContactCreateRequest'
      responses:
        201:
          description: The contact was created successfully
          examples: 
            application/json:
              id: e1300cbc-e73f-4fb3-a0a8-298e8a577802
              firstName: John
              lastName: Smith
          schema:
            $ref: '#/definitions/Contact'
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: Unexpected error
    
    get:
      tags:
        - Contacts
      summary: Returns a list of contacts
      parameters: 
        - $ref: '#/parameters/_offset'
        - $ref: '#/parameters/_limit'
      responses:
        200:
          description: a page of contacts
          schema:
            $ref: '#/definitions/ContactListResponse'
        400:
          description: Invalid request (including invalid query params)
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: Unexpected error
          
  /contacts/{contactId}:
    get:
      tags:
        - Contacts
      summary: Returns a specific contact
      parameters: 
        - $ref: '#/parameters/contactIdPathParam'
      responses:
        200:
          description: a contact
          schema: 
            $ref: '#/definitions/Contact'
        400:
          description: Invalid request (including invalid query params)
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: No Contact found for the specified id
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: PBE0001
              errorMessage: "PBE0001: No Contact found with id 'e1300cbc-e73f-4fb3-a0a8-298e8a577802'"
        500:
          description: Unexpected error
            
    put:
      tags:
        - Contacts
      summary: Update a specific contact
      parameters: 
        - $ref: '#/parameters/contactIdPathParam'
        - name: Contact
          in: body
          description: The JSON representation of a Contact
          required: true
          schema:
            $ref: '#/definitions/Contact'
      responses:
        200:
          description: a contact
          schema: 
            $ref: '#/definitions/Contact'
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: No Contact found for the specified id
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: PBE0001
              errorMessage: "PBE0001: No Contact found with id 'e1300cbc-e73f-4fb3-a0a8-298e8a577802'"
        500:
          description: Unexpected error
            
    delete:
      tags:
        - Contacts
      summary: Delete a specific Contact
      description: Deletes the Contact with the specified id.
      parameters: 
        - $ref: '#/parameters/contactIdPathParam'
      responses:
        204:
          description: The Contact was successfully deleted
        404:
          description: No Contact found for the specified id
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: PBE0001
              errorMessage: "PBE0001: No Contact found with id 'e1300cbc-e73f-4fb3-a0a8-298e8a577802'"
        500:
          description: Unexpected error
    

  /contacts/{contactId}/phonenumbers:
    post:
      tags:
        - Phone Numbers
      summary: Add a new phone number to a contact
      parameters: 
        - $ref: '#/parameters/contactIdPathParam'
        - name: Phone Number
          in: body
          description: The JSON representation of a phone number
          required: true
          schema:
            $ref: '#/definitions/PhoneNumber'
      responses:
        201:
          examples: 
            application/json:
              type: iPhone
              number: "07423678985"
          description: The phone number was successfully added to the contact
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: No Contact found for the specified id
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: PBE0001
              errorMessage: "PBE0001: No Contact found with id 'e1300cbc-e73f-4fb3-a0a8-298e8a577802'"
        409:
          description: A phone number with the specified 'type' field already exists in this Contact.
          examples: 
            application/json:
              errorCode: PBE0003
              errorMessage: "PBE0003: A Phone Number with type 'iPhone' already exists in this Contact."
        500:
          description: Unexpected error
          
    get:
      tags: 
        - Phone Numbers
      summary: Returns a list of phone numbers for a specific contact
      parameters: 
        - $ref: '#/parameters/contactIdPathParam'
        - $ref: '#/parameters/_offset'
        - $ref: '#/parameters/_limit'
      responses:
        200:
          description: a page of phone numbers
          schema:
            $ref: '#/definitions/PhoneNumberListResponse'
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: No Contact found for the specified id
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: PBE0001
              errorMessage: "PBE0001: No Contact found with id 'e1300cbc-e73f-4fb3-a0a8-298e8a577802'"
        500:
          description: Unexpected error
            
  /contacts/{contactId}/phonenumbers/{type}:
    get:
      tags: 
        - Phone Numbers
      summary: Returns a specific phone number for a contact
      parameters: 
        - $ref: '#/parameters/contactIdPathParam'
        - $ref: '#/parameters/phoneNumberTypePathParam'
      responses:
        200:
          description: A phone number
          schema:
            $ref: '#/definitions/PhoneNumber'
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: No Contact or Phone Number found for the specified id
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: PBE0001
              errorMessage: "PBE0001: No Contact found with id 'e1300cbc-e73f-4fb3-a0a8-298e8a577802'"
        500:
          description: Unexpected error
            
    put:
      tags: 
        - Phone Numbers
      summary: Update a phone number for a contact
      description: Only the **number** field of the object can be updated.  Any other updates will be ignored.
      parameters: 
        - $ref: '#/parameters/contactIdPathParam'
        - $ref: '#/parameters/phoneNumberTypePathParam'
        - name: Phone Number
          in: body
          description: The JSON representation of a Contact
          required: true
          schema:
            $ref: '#/definitions/PhoneNumber'
      responses:
        200:
          description: The phone number was successfully updated
          schema:
            $ref: '#/definitions/PhoneNumber'
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: No Contact or Phone Number found for the specified id
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: PBE0001
              errorMessage: "PBE0001: No Contact found with id 'e1300cbc-e73f-4fb3-a0a8-298e8a577802'"
        500:
          description: Unexpected error
    
    delete:
      tags: 
        - Phone Numbers
      summary: Removes a phone number from a contact
      parameters: 
        - $ref: '#/parameters/contactIdPathParam'
        - $ref: '#/parameters/phoneNumberTypePathParam'
      responses:
        204:
          description: The phone number was successfully removed from the contact
        400:
          description: Invalid request
          schema:
            $ref: '#/definitions/ErrorResponse'
        404:
          description: No Contact or Phone Number found for the specified id
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: PBE0001
              errorMessage: "PBE0001: No Contact found with id 'e1300cbc-e73f-4fb3-a0a8-298e8a577802'"
        500:
          description: Unexpected error
    
    
            
################################################################################
# Parameters
################################################################################
parameters:

  _offset:
    name: _offset
    in: query
    description: number of records to skip when paging
    type: number
    minimum: 0
    default: 0

  _limit:
    name: _limit
    in: query
    description: maximum number of records to return when paging
    type: number
    minimum: 1
    maximum: 100
    default: 25

  contactIdPathParam:
    name: contactId
    in: path
    type: string
    minLength: 36
    maxLength: 36
    format: uuid    
    description: Contact Id
    required: true
    
  phoneNumberTypePathParam:
    name: type
    in: path
    type: string
    minLength: 1
    maxLength: 32
    description: Phone number type
    required: true

################################################################################
# Definitions
################################################################################
definitions:
  PhoneNumber:
    required: 
      - type
      - number
    properties:
      type:
        type: string
        description: an identifier for the type of phone number
      number:
        type: string
        description: a phone number
        pattern: '\d{1,32}'
    example:
      type: iPhone
      number: 07423678985
      
  PhoneNumberListResponse:
    type: object
    properties:
      results:
        type: array
        items:
          $ref: '#/definitions/PhoneNumber'
      totalCount:
        type: number
        description: total number of results available for paging
        example: 10
    

  ContactCreateRequest:
    required: 
      - firstName
    properties:
      firstName:
        type: string
      lastName:
        type: string
    example: 
      firstName: John
      lastName: Smith
        
  Contact:
    required: 
      - firstName
    properties:
      id:
        type: string
        format: uuid
        description: a unique identifier for the contact
      firstName:
        type: string
      lastName:
        type: string
        
  ContactListResponse:
    type: object
    properties:
      results:
        type: array
        items:
          $ref: '#/definitions/Contact'
      totalCount:
        type: number
        description: total number of results available for paging

  ErrorResponse:
    type: object
    properties:
      errorCode:
        type: string
        example: PBE0004
      errorMessage:
        type: string
        example: "PBE0004: The request was invalid: '[VER0002: The type field cannot be null]'"


